"""initial

Revision ID: 4935ce6f3c8f
Revises:
Create Date: 2023-12-10 15:15:24.954744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from datetime import time


# revision identifiers, used by Alembic.
revision: str = "4935ce6f3c8f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    doctors = op.create_table(
        "doctors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("specialization", sa.String(), nullable=False),
        sa.Column("busy_time", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
    doctors_data = [
        {
            "first_name": "Dmitry",
            "last_name": "Gorelov",
            "specialization": "Pediatrician",
            "busy_time": [
                {"start_time": "18:40", "end_time": "18:50"},
                {"start_time": "14:40", "end_time": "15:50"},
                {"start_time": "10:30", "end_time": "10:50"},
                {"start_time": "16:40", "end_time": "17:20"},
                {"start_time": "20:05", "end_time": "20:20"},
            ]
        },
        {
            "first_name": "Vasya",
            "last_name": "Pupkin",
            "specialization": "Ophthalmologist",
            "busy_time": [
                {"start_time": "09:10", "end_time": "09:20"}
            ]
        },
        {
            "first_name": "Boris",
            "last_name": "Britva",
            "specialization": "Surgeon",
            "busy_time": [
                {"start_time": "09:00", "end_time": "09:50"}
            ]
        },
    ]
    op.bulk_insert(doctors, doctors_data)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("doctors")
    # ### end Alembic commands ###
